//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCommon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Misc : global::System.Configuration.ApplicationSettingsBase {
        
        private static Misc defaultInstance = ((Misc)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Misc())));
        
        public static Misc Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime WindowsNotificationLastCheckedTime {
            get {
                return ((global::System.DateTime)(this["WindowsNotificationLastCheckedTime"]));
            }
            set {
                this["WindowsNotificationLastCheckedTime"] = value;
            }
        }
    }
}
