//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USE_OPENAI {
            get {
                return ((bool)(this["USE_OPENAI"]));
            }
            set {
                this["USE_OPENAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AZURE_OPENAI {
            get {
                return ((bool)(this["AZURE_OPENAI"]));
            }
            set {
                this["AZURE_OPENAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPENAI_API_KEY {
            get {
                return ((string)(this["OPENAI_API_KEY"]));
            }
            set {
                this["OPENAI_API_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text-embedding-3-small")]
        public string EMBEDDING_MODEL_NAME {
            get {
                return ((string)(this["EMBEDDING_MODEL_NAME"]));
            }
            set {
                this["EMBEDDING_MODEL_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gpt-4-1106-preview")]
        public string CHAT_MODEL_NAME {
            get {
                return ((string)(this["CHAT_MODEL_NAME"]));
            }
            set {
                this["CHAT_MODEL_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ja_core_news_lg")]
        public string SPACY_MODEL_NAME {
            get {
                return ((string)(this["SPACY_MODEL_NAME"]));
            }
            set {
                this["SPACY_MODEL_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USE_VECTOR_DB {
            get {
                return ((bool)(this["USE_VECTOR_DB"]));
            }
            set {
                this["USE_VECTOR_DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VECTOR_DB_URL {
            get {
                return ((string)(this["VECTOR_DB_URL"]));
            }
            set {
                this["VECTOR_DB_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TAGS {
            get {
                return ((string)(this["TAGS"]));
            }
            set {
                this["TAGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USE_PYTHON {
            get {
                return ((bool)(this["USE_PYTHON"]));
            }
            set {
                this["USE_PYTHON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Python312\\python312.dll")]
        public string PYTHON_DLL_PATH {
            get {
                return ((string)(this["PYTHON_DLL_PATH"]));
            }
            set {
                this["PYTHON_DLL_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BACKUP_GENERATIONS {
            get {
                return ((int)(this["BACKUP_GENERATIONS"]));
            }
            set {
                this["BACKUP_GENERATIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AZURE_OPENAI_ENDPOINT {
            get {
                return ((string)(this["AZURE_OPENAI_ENDPOINT"]));
            }
            set {
                this["AZURE_OPENAI_ENDPOINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USE_PYTHON_FLASK {
            get {
                return ((bool)(this["USE_PYTHON_FLASK"]));
            }
            set {
                this["USE_PYTHON_FLASK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_DESCRIPTION {
            get {
                return ((bool)(this["AUTO_DESCRIPTION"]));
            }
            set {
                this["AUTO_DESCRIPTION"] = value;
            }
        }
    }
}
